#!/usr/bin/env bash
# Single source of truth for Stage-3. This file is sourced before raylet startup
# on both nodes and again by every nested trainer wrapper. Values are
# deliberately authoritative rather than inheritable: a versioned launch must
# not silently drift because of an operator shell or a legacy base wrapper.

CONFIG_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export WAM_REPO_ROOT=${WAM_REPO_ROOT:-$(cd "$CONFIG_DIR/../../.." && pwd)}
export WAM_CONFIG_CONTRACT_VERSION=wnm-3d-stage3-navigation-grpo-r1
export WAM_CONFIG_CONTRACT_VERIFIER=${WAM_CONFIG_CONTRACT_VERIFIER:-$CONFIG_DIR/verify_config.py}
export WAM_VARIANT_NAME=wnm-3d-stage3-navigation-grpo
export WAM_REWARD_FUNCTION_PATH=${WAM_REWARD_FUNCTION_PATH:-$CONFIG_DIR/reward.py}

# Fresh RL initialization and immutable dataset decode contract. The data
# contract may come from a checkpoint other than the policy initializer. The
# shared launcher verifies that config.json, metadata.json, and the canonical
# action_normalization.json are byte-identical before allowing that split.
export WNM3D_INITIAL_CHECKPOINT=${WNM3D_INITIAL_CHECKPOINT:-}
export WAM_DATA_CONTRACT_CHECKPOINT=${WAM_DATA_CONTRACT_CHECKPOINT:-$WNM3D_INITIAL_CHECKPOINT}
export WAM_MODEL_ARCHITECTURE=WNM3D
export WAM_DATA_ROOT=${WAM_DATA_ROOT:-}
export WAM_EXPECTED_VAL_SIZE=0
export WAM_PROFILE_USE_TRAIN_AS_VAL=true
export WAM_RESUME_MODE=disable

# Sampler and optimizer. Machine topology and topology-dependent batch sizes
# are resolved separately by resources.env.sh.
export NUM_INFERENCE_STEPS=16
export ENABLE_DIT_CACHE=true
export ENABLE_CFG=true
export CFG_SCALE=5.0
export DYNAMIC_CACHE_SCHEDULE=false
export WAM_NOISE_LEVEL=0.7
export WAM_ACTION_NOISE_LEVEL=0.10
export WAM_INIT_SAME_NOISE=true
export WAM_NUM_INFERENCE_STEPS=16
export WAM_TRUE_CFG_SCALE=5.0
export WAM_ACTION_BACKBONE_GRAD_GAIN=1.0
export WAM_LEARNING_RATE=5e-6
export WAM_ACTION_LOG_PROB_WEIGHT=0.25
export WAM_VISUAL_CLIP_RATIO=0.0005
export WAM_ACTION_CLIP_RATIO=0.01
export WAM_ROLLOUT_N=16
export WAM_VAL_ROLLOUT_N=1
export WAM_ROLLOUT_GROUP_SIZE=16
export WAM_ROLLOUT_MAX_NUM_SEQS=8
export WAM_LAYER_CONDITIONED_CREDIT_ENABLED=true
export WAM_LAYER_CONDITIONED_BRANCHES_PER_STRATUM=4
export WAM_TOTAL_EPOCHS=1
export WAM_VAL_BEFORE_TRAIN=true
export WAM_TEST_FREQ=50
export WAM_SAVE_FREQ=200
export WAM_VALIDATION_MAX_MEDIA_SAMPLES=4
export WAM_VALIDATION_CHECKPOINT_GUARD=true
export WAM_ROLLOUT_REPLAY_ATOL=1000000000
export WAM_ROLLOUT_REPLAY_FAIL_ON_MISMATCH=false

# Navigation reward and chunk credit.
export WAM_ACTION_REWARD_MIN=-1.0
export WAM_ACTION_REWARD_MAX=1.0
export WAM_ACTION_CHUNK_CREDIT_ENABLED=true
export WAM_ACTION_CHUNK_SIZE=8
export WAM_ACTION_CHUNK_WEIGHTS=1,0.5,0.25,0.125
export WAM_ACTION_CHUNK_REWARD_MODE=signed_progress_length
export WAM_SIGNED_PROGRESS_WEIGHT=0.70
export WAM_SYMMETRIC_LENGTH_WEIGHT=0.15
export WAM_SIGNED_GOAL_WEIGHT=0.15
export WAM_SIGNED_PROGRESS_DENOM_FLOOR_M=0.50
export WAM_SYMMETRIC_LENGTH_SCALE=0.50
export WAM_SYMMETRIC_LENGTH_FLOOR_M=0.10
export WAM_ROUTE_DEVIATION_WEIGHT=0.35
export WAM_ROUTE_DEVIATION_FREE_RADIUS_M=0.75
export WAM_ROUTE_DEVIATION_SCALE_M=1.50
export WAM_REVERSE_DIRECTION_WEIGHT=0.30
export WAM_ROUTE_MOTION_FLOOR_M=0.03
export WAM_GOAL_SCORE_USE_POTENTIAL_DELTA=true
export WAM_GOAL_ENTRY_BONUS=0.15
export WAM_NDTW_WEIGHT=0.0
export WAM_GEODESIC_BACKTRACK_WEIGHT=0.0
export WAM_PATH_EFFICIENCY_POWER=2.0
export WAM_FLOW_ACTION_VISUAL_WEIGHT=0.05
export WAM_FLOW_ACTION_ACTION_WEIGHT=0.05
export WAM_FLOW_ACTION_CALIBRATION_PATH=${WAM_FLOW_ACTION_CALIBRATION_PATH:-$CONFIG_DIR/flow_action_calibration.json}

# GN0 STOP semantics and anti-evasion shaping.
export WAM_CHUNK_MOTION_STOP_ENABLED=true
export WAM_CHUNK_MOTION_STOP_THRESHOLD_M=0.15
export WAM_CHUNK_MOTION_STOP_METRIC=path_length
export WAM_DEPLOY_STOP_SEMANTICS_ENABLED=true
export WAM_DEPLOY_ACTION_NUM=8
export WAM_DEPLOY_STOP_EPS=1e-3
export WAM_CORRECT_STOP_BONUS=0.15
export WAM_PREMATURE_STOP_PENALTY=0.75
export WAM_PREMATURE_STOP_NAV_PENALTY_WEIGHT=0.25
export WAM_PREMATURE_STOP_DISTANCE_SCALING_ENABLED=true
export WAM_PREMATURE_STOP_DISTANCE_DEADBAND_M=0.25
export WAM_PREMATURE_STOP_DISTANCE_TAU_M=2.0
export WAM_PREMATURE_STOP_PENALTY_DISTANCE_ADD=0.25
export WAM_PREMATURE_STOP_NAV_DISTANCE_ADD=0.75
export WAM_STOP_WELL_ENABLED=true
export WAM_STOP_WELL_ENERGY_WEIGHT=0.20
export WAM_STOP_WELL_XY_DEADZONE_M=0.00
export WAM_STOP_WELL_YAW_WEIGHT=0.18
export WAM_STOP_WELL_YAW_DEADZONE_RAD=0.02
export WAM_STOP_WELL_YAW_SCALE_RAD=0.25
export WAM_STOP_REWARD_MIN=-1.0
export WAM_STOP_REWARD_MAX=1.0
export WAM_STOP_LOSS_WEIGHT=1.00
export WAM_STOP_USE_CHUNK_WEIGHTS=false
export WAM_STOP_LEFT_GOAL_PENALTY=-1.00
export WAM_STOP_CONTINUED_PENALTY=0.0

# Linear yaw guard. Path/rate are translation-only; GT heading also observes
# pure-yaw controls. The total penalty is capped per credit chunk.
export WAM_YAW_CREDIT_ENABLED=true
export WAM_YAW_SCORE_MODE=linear_guard
export WAM_YAW_PATH_CONSISTENCY_WEIGHT=0.16
export WAM_YAW_RATE_CONSISTENCY_WEIGHT=0.10
export WAM_YAW_GROSS_GT_WEIGHT=0.08
export WAM_YAW_FREE_ANGLE_DEG=10
export WAM_YAW_PATH_HARD_ANGLE_DEG=45
export WAM_YAW_RATE_FREE_ANGLE_DEG=8
export WAM_YAW_RATE_HARD_ANGLE_DEG=35
export WAM_YAW_GT_FREE_ANGLE_DEG=12
export WAM_YAW_GROSS_ANGLE_DEG=60
export WAM_YAW_MOTION_FLOOR_M=0.03
export WAM_YAW_ROTATION_FLOOR_RAD=0.01
export WAM_YAW_SPIKE_MAX_MIX=0.50
export WAM_YAW_TOTAL_PENALTY_CAP=0.24

# GN0 collision clipping/recovery remains inside navigation reward only.
export WAM_OCCUPANCY_THRESHOLD=200
export WAM_OCCUPANCY_MARGIN_PX=2
export WAM_GEODESIC_OCCUPANCY_MARGIN_PX=0
export WAM_GEODESIC_SNAP_RADIUS_PX=4
export WAM_COLLISION_CREDIT_ENABLED=false
export WAM_COLLISION_LOSS_WEIGHT=0.0
export WAM_COLLISION_USE_CHUNK_WEIGHTS=false
export WAM_TERMINAL_SAFETY_ADVANTAGE_ENABLED=false
export WAM_COLLISION_STOP_ENABLED=false
export WAM_COLLISION_RECOVERY_ENABLED=true
export WAM_DEPLOYMENT_COLLISION_MARGIN_PX=4
export WAM_COLLISION_PENALTY_WEIGHT=0.60
export WAM_COLLISION_REPEAT_PENALTY_WEIGHT=0.10
export WAM_COLLISION_REPEAT_PENALTY_CAP_COUNT=2
export WAM_COLLISION_RECOVERY_BONUS_WEIGHT=0.10
export WAM_COLLISION_RECOVERY_CLEARANCE_PX=6
export WAM_COLLISION_RECOVERY_MIN_ESCAPE_M=0.20
export WAM_COLLISION_RECOVERY_FULL_ESCAPE_M=0.40
export WAM_COLLISION_RECOVERY_TAIL_FREE_STEPS=2
export WAM_COLLISION_RECOVERY_GRACE_ENABLED=true
export WAM_COLLISION_SOFT_ENABLED=true
export WAM_COLLISION_SOFT_MARGIN_PX=6
export WAM_COLLISION_SOFT_PENALTY_WEIGHT=0.25
export WAM_REWARD_METRICS_COMPACT=true
